name: Tag rollup check
description: Check commits since a moving tag (run nightly or before deployment)
author: Terje Sandstrom
branding:
  icon: git-commit
  color: blue

inputs:
  tag:
    description: Tag name to compare (e.g., last-deploy or last-deploy/prod)
    required: true
    default: last-deploy
  initial_as_changes:
    description: If no tag exists, treat as changes (true) or no changes (false)
    default: "true"

outputs:
  has_changes:
    description: true if HEAD is ahead of the tag (or initial_as_changes == true and tag missing)
    value: ${{ steps.check.outputs.has_changes }}
  base_tag:
    description: The tag name if present, else empty
    value: ${{ steps.check.outputs.base_tag }}
  ahead:
    description: Number of commits ahead of tag
    value: ${{ steps.check.outputs.ahead }}
  current_branch:
    description: The current branch or ref
    value: ${{ steps.check.outputs.current_branch }}

runs:
  using: composite
  steps:
    - shell: bash
      run: git fetch --tags --force

    - id: check
      shell: bash
      run: |
        set -euo pipefail
        tag="${{ inputs.tag }}"
        initial="${{ inputs.initial_as_changes }}"

        echo "📦 Fetching tags and checking branch context…"
        git fetch --tags --force >/dev/null 2>&1 || true

        # Get current branch/ref info for debugging
        current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "HEAD")
        current_sha=$(git rev-parse HEAD)
        
        echo "Current branch: $current_branch"
        echo "Current SHA: $current_sha"
        echo "Looking for tag: $tag"

        base=""
        ahead=0

        if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
          tag_sha=$(git rev-parse "refs/tags/$tag")
          echo "✓ Found tag '$tag' at SHA: $tag_sha"
          
          # Check if tag is an ancestor of HEAD
          if git merge-base --is-ancestor "refs/tags/$tag" HEAD 2>/dev/null; then
            ahead=$(git rev-list --count "refs/tags/$tag"..HEAD)
            base="$tag"
            reason="$ahead commit(s) since '$tag'."
            echo "✓ Tag is ancestor of HEAD, $ahead commits ahead"
          else
            echo "⚠ Tag '$tag' exists at $tag_sha but is NOT an ancestor of HEAD ($current_sha)"
            if [ "$initial" = "true" ]; then
              ahead=$(git rev-list --count HEAD)
              reason="Tag '$tag' found but not in current branch history. Treating as initial run ($ahead commits)."
            else
              ahead=0
              reason="Tag '$tag' found but not in current branch history. initial_as_changes=false, so no run."
            fi
          fi
        else
          echo "✗ Tag '$tag' not found"
          if [ "$initial" = "true" ]; then
            ahead="$(git rev-list --count HEAD)"
            reason="No tag '$tag' found; treating as initial run."
          else
            ahead="0"
            reason="No tag '$tag' found; initial_as_changes=false, so no run."
          fi
        fi

        if [ "$ahead" -gt 0 ]; then
          has_changes="true"
        else
          has_changes="false"
        fi

        {
          echo "has_changes=$has_changes"
          echo "base_tag=$base"
          echo "ahead=$ahead"
          echo "current_branch=$current_branch"
        } >> "$GITHUB_OUTPUT"
        
        # Summary
        {
          echo "### Tag rollup check"
          echo "- **Branch**: \`$current_branch\` @ \`${current_sha:0:7}\`"
          echo "- **Tag**: \`$tag\`"
          echo "- **Found tag**: \`${base:-〈none〉}\`"
          echo "- **Commits ahead**: \`$ahead\`"
          echo "- **Decision**: \`${has_changes}\`"
          echo ""
          echo "$reason"
        } >> "$GITHUB_STEP_SUMMARY"

        # Also echo to logs for quick visibility
        echo "Branch=$current_branch @ ${current_sha:0:7}, has_changes=$has_changes, base_tag=${base:-none}, ahead=$ahead — $reason"
